In [2]:
import numpy as np

NumPy Array Creation

In [6]:
# We can create a NumPy array using a Python List

list = [1,2,3,4,5]
numpy_list = np.array(list)
print(numpy_list, " | ", type(numpy_list))

[1 2 3 4 5]  |  <class 'numpy.ndarray'>


In [7]:
# The np.zeros() function allows us to create an array filled with all zeros

array = np.zeros(4)
print(array, " | ", type(array))

[0. 0. 0. 0.]  |  <class 'numpy.ndarray'>


In [10]:
# The np.arange() function returns an array with values within a specified interval

# 1. create an array with values from 0 to 4
array = np.arange(5)
print(array, " | ", type(array))

# 2. create an array with values from 1 to 8 with a step of 2
array = np.arange(1, 9, 2)
print(array, " | ", type(array))

[0 1 2 3 4]  |  <class 'numpy.ndarray'>
[1 3 5 7]  |  <class 'numpy.ndarray'>


In [17]:
# The np.random.rand() function is used to create an array of random numbers.

array = np.random.random(5)
print(array, " | ", type(array))

array = np.random.randint(1,10,5)
print(array, " | ", type(array))

[0.44004628 0.68230064 0.67010898 0.77394238 0.31288453]  |  <class 'numpy.ndarray'>
[6 1 5 6 4]  |  <class 'numpy.ndarray'>


In [21]:
# To create an empty NumPy array, we use the np.empty() function.

array = np.empty(5)
print(array, " | ", type(array))

[0.44004628 0.68230064 0.67010898 0.77394238 0.31288453]  |  <class 'numpy.ndarray'>


NumPy N-D Array Creation

In [24]:
# We can create a NumPy array using a Python List

# create a 2D array with 2 rows and 4 columns
array = np.array([[1, 2, 3, 4],
                  [5, 6, 7, 8]])
print(array, " | ", type(array) , " | ", array.shape)

[[1 2 3 4]
 [5 6 7 8]]  |  <class 'numpy.ndarray'>  |  (2, 4)


In [26]:
# The np.zeros() function allows us to create N-D arrays filled with all zeros. 

array = np.zeros((2,4))
print(array, " | ", type(array) , " | ", array.shape)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]]  |  <class 'numpy.ndarray'>  |  (2, 4)


In [27]:
# In NumPy, we can use the np.full() function to create a multidimensional array with a specified value.

array = np.full((2,4),5)
print(array, " | ", type(array) , " | ", array.shape)

[[5 5 5 5]
 [5 5 5 5]]  |  <class 'numpy.ndarray'>  |  (2, 4)


In [31]:
# The np.random.rand() function is used to create an array of random numbers.

array = np.random.rand(2,4)
print(array, " | ", type(array) , " | ", array.shape)

array = np.random.randint(1,10,(2,4))
print(array, " | ", type(array) , " | ", array.shape)

[[0.73945464 0.74320528 0.47910781 0.59419604]
 [0.7387578  0.37333711 0.04367394 0.16664246]]  |  <class 'numpy.ndarray'>  |  (2, 4)
[[6 9 9 1]
 [7 4 8 7]]  |  <class 'numpy.ndarray'>  |  (2, 4)


In [32]:
# To create an empty N-D NumPy array, we use the np.empty() function.

array = np.empty((2,4))
print(array, " | ", type(array) , " | ", array.shape)

[[0.09269583 0.329177   0.26522773 0.09196764]
 [0.82855745 0.98027936 0.16072105 0.01538527]]  |  <class 'numpy.ndarray'>  |  (2, 4)
